services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./tasks.db
    volumes:
      - ./backend:/app
      # Mount a named volume specifically for the .venv
      - backend_venv:/app/.venv
      - backend_data:/app/data
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start
    depends_on:
      - backend

  db:
    image: alpine:latest
    command: sleep infinity
    volumes:
      - backend_data:/data

volumes:
  backend_data:
  backend_venv:
