import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faPlus,
  faEdit,
  faCheck,
  faTrash,
  faInbox,
  faPlayCircle,
  faCheckCircle,
  faFilter,
  faSearch,
  faSort,
  faTasks,
  faCalendar,
  faClock,
  faUser,
  faFlag,
  faArrowUp,
  faArrowDown,
  faEllipsisV,
  faChevronDown,
  faChevronUp,
  faTimes,
  faSave,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faHome,
  faCog,
  faBell,
  faQuestionCircle,
  faHeading,
  faGripVertical,
  faHandRock,
  faBoxArchive
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
  faPlus,
  faEdit,
  faCheck,
  faTrash,
  faInbox,
  faPlayCircle,
  faCheckCircle,
  faFilter,
  faSearch,
  faSort,
  faTasks,
  faCalendar,
  faClock,
  faUser,
  faFlag,
  faArrowUp,
  faArrowDown,
  faEllipsisV,
  faChevronDown,
  faChevronUp,
  faTimes,
  faSave,
  faSpinner,
  faExclamationTriangle,
  faInfoCircle,
  faHome,
  faCog,
  faBell,
  faQuestionCircle,
  faHeading,
  faGripVertical,
  faHandRock,
  faBoxArchive
);

export * from '@fortawesome/react-fontawesome';